### ISSUE TITLE
wifi 驱动没有成功识别

### ISSUE THREAD

**Issue by zkzhao** [LiXiaobo1995/ASUS-TUF-GAMING-B460M-PLUS-WI-FI#3]
你好，其他驱动都识别正常，想知道wifi的驱动如何操作才能正常识别

**Comment by LiXiaobo1995** [comment]
是没连上WiFi还是没有驱动

**Comment by zkzhao** [comment]
![image](https://user-images.githubusercontent.com/1487795/112635428-0d090480-8df9-11eb-8b02-4c156f305e5b.png)

![image](https://user-images.githubusercontent.com/1487795/112635389-ff537f00-8df8-11eb-9a79-48e405d3cd10.png)


这样应该是没有驱动吧？

**Comment by LiXiaobo1995** [comment]
上传了个新的试试

**Comment by zkzhao** [comment]
感谢大神无私奉献，问题已解决
